export const RESET_APP_STATE = 'RESET_APP_STATE'

export const SAVE_SECRETS = 'SAVE_SECRETS'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'

export const SYNC_READ_NOTIFICATIONS_WITH_FIRESTORE = 'SYNC_READ_NOTIFICATIONS_WITH_FIRESTORE'

export const SYNC_UNREAD_NOTIFICATIONS_WITH_FIRESTORE = 'SYNC_UNREAD_NOTIFICATIONS_WITH_FIRESTORE'
